AWSTemplateFormatVersion: '2010-09-09'
Description: 'Monitoring infrastructure for PermaNet production deployment'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Environment name

Resources:
  # CloudWatch Log Group
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/permanet/${Environment}'
      RetentionInDays: 30

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'CPU utilization is high'
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic

  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Memory utilization is high'
      MetricName: MemoryUtilization
      Namespace: 'Custom/PermaNet'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic

  APILatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'API latency is high'
      MetricName: node_response_time
      Namespace: 'Custom/PermaNet'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic

  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Error rate is high'
      MetricName: node_health_check_errors
      Namespace: 'Custom/PermaNet'
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic

  # SNS Topic for Alerts
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'PermaNet Alerts'
      TopicName: !Sub 'permanet-${Environment}-alerts'

  # IAM Role for CloudWatch Agent
  CloudWatchAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  # Dashboard for metrics visualization
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'permanet-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["Custom/PermaNet", "node_health_score"]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Node Health Score"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["Custom/PermaNet", "node_response_time"]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Node Response Time"
              }
            }
          ]
        }

Outputs:
  LogGroupName:
    Description: Name of the CloudWatch Log Group
    Value: !Ref ApplicationLogGroup
  AlertsTopicArn:
    Description: ARN of the SNS Topic for alerts
    Value: !Ref AlertsTopic
  CloudWatchAgentRoleArn:
    Description: ARN of the CloudWatch Agent Role
    Value: !GetAtt CloudWatchAgentRole.Arn