AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Secrets Manager resources for PermaNet'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

Resources:
  PermaNetSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/${Environment}/permanet/credentials'
      Description: 'Credentials for PermaNet services'
      SecretString: !Sub |
        {
          "edge_node_private_key": "PLACEHOLDER",
          "marketplace_private_key": "PLACEHOLDER",
          "coordinator_contract_address": "PLACEHOLDER",
          "marketplace_contract_address": "PLACEHOLDER",
          "poi_contract_address": "PLACEHOLDER",
          "pou_contract_address": "PLACEHOLDER"
        }

  SecretsAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Ref PermaNetSecrets

Outputs:
  SecretArn:
    Description: ARN of the created secret
    Value: !Ref PermaNetSecrets
  
  SecretsAccessRoleArn:
    Description: ARN of the IAM role for accessing secrets
    Value: !GetAtt SecretsAccessRole.Arn