webrtc:
  stun_servers:
    - urls: 'stun:stun.l.google.com:19302'
    - urls: 'stun:stun1.l.google.com:19302'
    - urls: 'stun:stun2.l.google.com:19302'
    - urls: 'stun:stun3.l.google.com:19302'
    - urls: 'stun:stun.stunprotocol.org:3478'
    - urls: 'stun:stun.voip.blackberry.com:3478'
  turn_servers:
    - urls: 'turn:openrelay.metered.ca:80'
      username: 'openrelayproject'
      credential: 'openrelayproject'
    - urls: 'turn:openrelay.metered.ca:443'
      username: 'openrelayproject'
      credential: 'openrelayproject'
    - urls: 'turn:open.relay.metered.ca:4445?transport=tcp'
      username: 'openrelayproject'
      credential: 'openrelayproject'
  ice_transport_policy: 'all'
  bundle_policy: 'balanced'
  rtcp_mux_policy: 'require'
  ice_candidate_pool_size: 10