global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'p2p_nodes'
    static_configs:
      - targets: ['p2p-node:3000']
    
  - job_name: 'ipfs'
    static_configs:
      - targets: ['ipfs:5001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # No centralized alerting - use local alerts only