# Sovereign RPC Network Configuration

# Network Parameters
network:
  name: "JoyNet-RPC"
  version: "1.0.0"
  chain_id: 1337  # JoyNet chain ID

# Node Configuration
node:
  min_stake: 1000000000000000000  # 1 JOY token
  heartbeat_interval: 60  # seconds
  cache_size: 10000000000  # 10GB
  max_peers: 50
  bootstrap_nodes:
    - "/ip4/bootstrap1.joynet/tcp/4001/p2p/QmBootstrap1"
    - "/ip4/bootstrap2.joynet/tcp/4001/p2p/QmBootstrap2"

# Data Layer
data:
  storage_type: "ipfs"
  replication_factor: 3
  min_providers: 2
  cache_ttl: 3600  # 1 hour
  pinning:
    enabled: true
    strategy: "distributed"  # Each node pins a subset of data
    min_pinners: 5  # Minimum nodes pinning each piece of data

# Security
security:
  tls_enabled: true
  jwt_expiry: 3600  # 1 hour
  rate_limit:
    requests_per_second: 100
    burst: 200
  
# Proof System
proof_system:
  type: "zkSNARK"
  verification_nodes: 3
  proof_ttl: 604800  # 1 week
  required_confirmations: 12

# Monitoring
monitoring:
  prometheus_enabled: true
  prometheus_port: 9090
  grafana_enabled: true
  grafana_port: 3000
  metrics:
    - node_uptime
    - request_latency
    - cache_hits
    - proof_verifications
    - data_availability
    - peer_count

# Governance
governance:
  dao_address: "${DAO_ADDRESS}"
  proposal_threshold: 100000000000000000000  # 100 JOY tokens
  voting_period: 604800  # 1 week
  timelock_delay: 172800  # 2 days

# Economic Parameters
economics:
  platform_fee: 2.5  # 2.5%
  node_reward_pool: 40  # 40% of fees
  staking_reward_pool: 30  # 30% of fees
  treasury_pool: 30  # 30% of fees
  min_node_stake: 1000000000000000000000  # 1000 JOY tokens