# Multi-chain Configuration for JoyNet

# Polygon Supernet Configuration
polygon:
  rpc_url: "https://rpc-supernet.polygon.technology"
  chain_id: 80001  # Update with actual Supernet chain ID
  account: "0x..."  # Update with deployer account
  private_key: "${POLYGON_PRIVATE_KEY}"  # Set via environment variable
  gas_limit: 6000000
  gas_price_strategy: "medium"

# Solana Configuration  
solana:
  rpc_url: "https://api.mainnet-beta.solana.com"
  commitment: "confirmed"
  timeout: 30
  keypair_path: "/keys/solana-keypair.json"
  program_id: "..."  # Update with deployed program ID

# IOTA Configuration
iota:
  node_url: "https://chrysalis-nodes.iota.org"
  local_pow: true
  timeout: 30
  mwm: 14  # Minimum weight magnitude
  depth: 3

# Contract Addresses & ABIs
contracts:
  # Polygon contracts
  polygon_address: "0x..."  # Update after deployment
  polygon_abi: "/workspace/POI/JoyNet/contracts/multichain/abi/PolygonSupernet.json"
  
  # Bridge contracts  
  solana_bridge: "0x..."  # Update after deployment
  iota_bridge: "0x..."    # Update after deployment

# Storage Configuration
storage:
  ipfs:
    gateway: "https://ipfs.infura.io:5001"
    api_key: "${IPFS_API_KEY}"
    timeout: 30
    pin: true

# Monitoring & Metrics
monitoring:
  log_level: "INFO"
  metrics_port: 9090
  health_check_interval: 60

# Performance Settings
performance:
  max_concurrent_tasks: 100
  queue_size: 1000
  retry_attempts: 3
  retry_delay: 5

# Security Settings
security:
  min_confirmations:
    polygon: 5
    solana: 32
    iota: 1
  timeout:
    transaction: 120
    confirmation: 300
  
# Bridge Settings
bridge:
  min_validators: 3
  required_confirmations: 2
  max_transfer_amount: "1000000000000000000"  # 1 ETH in wei
  cooldown_period: 300  # 5 minutes between large transfers