---
# JoyNet Compute Node Configuration

# Node settings
node:
  type: "compute"  # compute, validator, or coordinator
  name: ${NODE_NAME}
  region: ${NODE_REGION}
  capacity_gb: 32
  max_tasks: 100
  min_reputation: 80

# Network settings
network:
  iota:
    node_url: ${IOTA_NODE_URL}
    mwm: 14  # Minimum weight magnitude
    depth: 3
  polygon:
    rpc_url: ${POLYGON_RPC_URL}
    chain_id: 1101  # Polygon Supernet
    gas_limit: 2000000

# Hardware requirements
hardware:
  min_cpu_cores: 8
  min_ram_gb: 16
  min_gpu_vram_gb: 8
  supported_gpus:
    - "NVIDIA RTX 3080"
    - "NVIDIA RTX 3090"
    - "NVIDIA A100"

# Model execution
inference:
  max_batch_size: 32
  timeout_seconds: 30
  max_concurrent_executions: 4
  supported_frameworks:
    - "pytorch"
    - "tensorflow"
    - "onnx"

# Security settings
security:
  require_zk_proof: true
  max_proof_delay_seconds: 60
  min_stake_joy: 1000
  slashing_percentage: 10