iota:
  node:
    url: ${IOTA_NODE_URL}
    api_version: v1
  streams:
    enabled: true
    validation:
      enabled: true
      contract_address: ${IOTA_VALIDATOR_ADDRESS}
    channel:
      seed: ${IOTA_CHANNEL_SEED}
      announcement_link: ${IOTA_ANNOUNCEMENT_LINK}
  security:
    tls_enabled: true
    certificate_path: ${IOTA_CERT_PATH}
    key_path: ${IOTA_KEY_PATH}
  monitoring:
    enabled: true
    metrics_port: 9091
    health_check_interval: 60