---
# JoyNet Marketplace Configuration

# Network settings
network:
  chain_id: 1101  # Polygon Supernet
  rpc_url: ${RPC_URL}
  ws_url: ${WS_URL}

# Token settings
token:
  address: ${JOY_TOKEN_ADDRESS}
  decimals: 18
  min_stake: 1000  # Minimum stake for model registration

# Marketplace parameters
marketplace:
  fee_percentage: 2.5  # Platform fee (%)
  min_price: 0.1  # Minimum model price in JOY
  max_price: 1000000  # Maximum model price in JOY
  listing_duration: 2592000  # 30 days in seconds

# Storage settings
storage:
  ipfs:
    gateway: ${IPFS_GATEWAY}
    pin_service: ${IPFS_PIN_SERVICE}
  arweave:
    gateway: ${ARWEAVE_GATEWAY}
    wallet_file: ${ARWEAVE_WALLET_PATH}

# Access control
access:
  free_tier:
    max_requests_per_day: 100
    max_model_size: 1073741824  # 1GB in bytes
  business_tier:
    requires_kyc: true
    min_stake: 10000
    unlimited_requests: true