---
network:
  host: ${RPC_HOST}
  jwt_secret: ${JWT_SECRET}
  rate_limit:
    requests_per_second: 100
    burst: 200
  security:
    ssl_enabled: true
    ssl_cert: ${SSL_CERT_PATH}
    ssl_key: ${SSL_KEY_PATH}
  monitoring:
    enabled: true
    health_check_interval: 300
    metrics_port: 9090
  iota:
    enabled: true
    node_url: ${IOTA_NODE_URL}
    stream_validation: true

nodes:
  registration:
    deposit_amount: 1000
    min_reputation: 80
  health:
    check_interval: 60
    threshold_score: 95
    max_response_time: 1000

security:
  rate_limiting:
    enabled: true
    window: 60
    max_requests: 1000
  ssl:
    enabled: true
    cert_path: ${SSL_CERT_PATH}
    key_path: ${SSL_KEY_PATH}
  jwt:
    enabled: true
    secret: ${JWT_SECRET}
    expiry: 3600

monitoring:
  prometheus:
    enabled: true
    port: 9090
  alerting:
    slack:
      enabled: ${SLACK_ALERTS_ENABLED}
      webhook: ${SLACK_WEBHOOK_URL}
    email:
      enabled: ${EMAIL_ALERTS_ENABLED}
      smtp_host: ${SMTP_HOST}
      smtp_port: ${SMTP_PORT}
      from: ${ALERT_FROM_EMAIL}
      to: ${ALERT_TO_EMAIL}