# JoyNet RPC Network Configuration

# Network Settings
network:
  name: "JoyNet RPC Network"
  version: "1.0.0"
  chain_id: 1  # Update based on deployment chain
  min_nodes: 5
  max_nodes: 100
  heartbeat_interval: 300  # 5 minutes in seconds
  scaling_threshold: 80  # 80% capacity threshold for scaling

# Node Settings
node:
  min_stake: "1000000000000000000000"  # 1000 JOY in wei
  max_capacity: 1000  # Max concurrent requests
  cache:
    max_size: "10GB"
    min_free_space: "5GB"
    cleanup_interval: 3600  # 1 hour in seconds
  replication:
    min_copies: 3
    max_copies: 7
    interval: 3600  # 1 hour in seconds
    geo_diversity: true

# Security Settings
security:
  ssl:
    enabled: true
    min_version: "TLS1.3"
  rate_limit:
    requests_per_second: 100
    burst: 200
  authentication:
    jwt:
      enabled: true
      expiry: 86400  # 24 hours in seconds
  input_validation:
    max_request_size: "10MB"
    allowed_methods:
      - "eth_call"
      - "eth_getBalance"
      - "eth_getTransactionCount"
      - "eth_getCode"
      - "eth_getStorageAt"
      - "eth_getBlockByHash"
      - "eth_getBlockByNumber"
      - "eth_getTransactionByHash"
      - "eth_getTransactionReceipt"
      - "eth_getLogs"
      - "net_version"
      - "web3_clientVersion"

# Data Storage
storage:
  type: "ipfs"
  settings:
    local_cache: true
    cache_size: "50GB"
    pin_duration: 604800  # 7 days in seconds
  backup:
    enabled: true
    interval: 86400  # 24 hours in seconds
    retention: 7  # days

# Monitoring
monitoring:
  metrics:
    enabled: true
    interval: 60  # 1 minute in seconds
    exporters:
      - type: "prometheus"
        port: 9090
      - type: "grafana"
        port: 3000
  logging:
    level: "info"
    format: "json"
    outputs:
      - type: "file"
        path: "/var/log/joynet/rpc.log"
      - type: "stdout"
  alerts:
    endpoints:
      - type: "email"
        address: "alerts@joynet.network"
      - type: "webhook"
        url: "https://alerts.joynet.network/webhook"
    thresholds:
      cpu_usage: 80
      memory_usage: 80
      disk_usage: 80
      error_rate: 5

# Performance
performance:
  caching:
    redis:
      enabled: true
      max_memory: "2GB"
      eviction_policy: "allkeys-lru"
  request_batching:
    enabled: true
    max_batch_size: 100
    batch_timeout: 100  # milliseconds

# Regions
regions:
  - name: "us-east"
    min_nodes: 5
    backup_regions:
      - "us-west"
      - "eu-central"
  - name: "us-west"
    min_nodes: 5
    backup_regions:
      - "us-east"
      - "ap-east"
  - name: "eu-central"
    min_nodes: 5
    backup_regions:
      - "us-east"
      - "ap-east"
  - name: "ap-east"
    min_nodes: 5
    backup_regions:
      - "eu-central"
      - "us-west"

# Proof Systems
proofs:
  types:
    - name: "ProofOfUse"
      min_verifiers: 3
      expiry: 2592000  # 30 days in seconds
    - name: "ProofOfIntegrity"
      min_verifiers: 3
      check_interval: 3600  # 1 hour in seconds
    - name: "ProofOfInference"
      min_verifiers: 3
      timeout: 300  # 5 minutes in seconds

# Token Economics
economics:
  platform_fee: 250  # 2.5% in basis points
  distribution:
    node_rewards: 40  # 40%
    staking_rewards: 30  # 30%
    community_treasury: 30  # 30%
  staking:
    min_amount: "1000000000000000000000"  # 1000 JOY
    lock_period: 604800  # 7 days in seconds
    reward_interval: 86400  # 24 hours in seconds

# Governance
governance:
  dao:
    voting_period: 604800  # 7 days in seconds
    execution_delay: 172800  # 2 days in seconds
    min_quorum: 51  # 51%
    proposal_threshold: "100000000000000000000000"  # 100,000 JOY

# Auto Recovery
recovery:
  enabled: true
  max_attempts: 3
  backoff_interval: 300  # 5 minutes in seconds
  triggers:
    - type: "node_failure"
      action: "replace_node"
    - type: "data_loss"
      action: "restore_from_backup"
    - type: "high_latency"
      action: "scale_region"

# Development
development:
  testnet:
    enabled: true
    faucet_amount: "100000000000000000000"  # 100 JOY
  logging:
    level: "debug"
  metrics:
    detailed: true