global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rpc_nodes'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: ${SSL_CERT_PATH}
      key_file: ${SSL_KEY_PATH}

  - job_name: 'iota_nodes'
    static_configs:
      - targets: ['localhost:9091']
    metrics_path: /metrics
    scheme: https
    tls_config:
      cert_file: ${IOTA_CERT_PATH}
      key_file: ${IOTA_KEY_PATH}

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rules:
  - alert: NodeHealthCritical
    expr: node_health_score < 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Node health critical"
      description: "Node {{ $labels.node_address }} health score is {{ $value }}"

  - alert: HighResponseTime
    expr: node_response_time_bucket{le="2000"} > 0.95
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time"
      description: "Node {{ $labels.node_address }} response time > 2s"